### ISSUE TITLE
[BUG] missing libpng in release 1.0.1

### ISSUE THREAD

**Issue by EndrII** [vedranMv/dataDashboard#2]
**Description of the bug**
Fail to run the datadashboard v1.0.1 on ubuntu 20.10 

```
andrei@X570-GAMING-X:~/Загрузки$ '/home/andrei/Загрузки/Data_dashboard-0.1.1-ubuntu-amd64/datadashboard.sh' 
/home/andrei/Загрузки/Data_dashboard-0.1.1-ubuntu-amd64/bin/datadashboard: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

 - OS and version: Ubuntu 20.10

**Additional context**
This is bug of the cqtdeployer tool. I am fixed it in [this](https://github.com/QuasarApp/CQtDeployer/commit/e67f42d9e484abf17974111631b03a910fde6f62) commit. 

See [this](https://github.com/QuasarApp/CQtDeployer/issues/446) issue and wait the new version of cqtdeployer(1.4.6.3) with fixes of this issue. Please, after update the cqtdeployer redeploy the Datadashboard. 

P.S.
Thanks you for using my deploy tool.

**Comment by EndrII** [comment]
I just checked version 0.2. Everything works correctly. I close this problem.
As I understand it, you manually threw libpng into the distributionKit folder, in the next version this will no longer be necessary.

**Comment by vedranMv** [comment]
Thank you for following up, I appreciate it.
Yes, in 0.2 libpng was manually copied.
