### ISSUE TITLE
libqt5datavisualization5-dev not available for Ubuntu 16.04

### ISSUE THREAD

**Issue by zlg9folira** [vedranMv/dataDashboard#6]
sudo apt-get install libqt5datavisualization5-dev on Debian Ubuntu 16.04 is not available as a pkg :
```
E: Unable to locate package qt5datavisualization5
```
Dependency cannot be installed.

**Comment by vedranMv** [comment]
Hi,

What are you trying to do? 

If you just want to run the project, you don't need to source this dependency as all runtime QT dependencies are bundled in a release file.  

If you want to compile from source, your easiest method is to use Ubuntu 20. For older versions, you need to download QT or compile it from source locally. ( https://github.com/vedranMv/dataDashboard#compilation-on-Linux)

**Comment by zlg9folira** [comment]
I got an ICM20948 IMU in hand which I would like to try your app to visualize its data. I downloaded your V1.0 release first, there I couldn't find `.sh` file as described it is needed to run the app. (Can you provide a link to the correct pre-compiled package?). Upon that failure, I tried following your compilation instruction which failed due to lack of dependency (including in your readme.md would help others to ignore compilation if they are on Ubuntu 16.04). One dependency is available only for `amd` arch (Debian included for Ubuntu 20.x)

**Comment by vedranMv** [comment]
Then a release is your best way forward

You need to download https://github.com/vedranMv/dataDashboard/releases/download/v1.0/Data_dashboard-1.0-ubuntu-amd64.zip

Then unzip it somewhere, and inside the unzipped folder, you will find .sh file.
